export const GET_POST_LOADING = "GET_POST_LOADING";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_FAILED = "GET_POST_FAILED";

export const ADD_POST_LOADING = "ADD_POST_LOADING";
export const ADD_POST_FAILED = "ADD_POST_FAILED";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";

